= REALEASE NOTES

== Changelog
=== Homebridge

==== v1.2.0
    * Realease Stable

==== v1.1.4

    * Bugfix : unregister Accessories si on a une erreur
    * Update Homebridge & HAP-NodeJS
    * Bugfix : Temperature isNaN -> 0
    * pré-support Sabotage
    * Bugfix : Interdire une valeur Null ou Undefined d'être envoyée à homekit
    
==== v1.1.2

    * Support basique Alarme : besoin d'une config coté plugin pour mapper les modes NUIT, ABSENT, PRESENT avec des ALARM_SET_MODE jeedom
    
==== v1.1.1 
    * Bugfix : Restauration des valeurs en cache au redémarrage
    * Bugfix : Bornage des valeurs du detecteur de lumière
    
==== v1.1.0 

    * Support des Plateformes Homebridge en mode expert (Cameras, autre...)
    * Documentation code
    * Freeze des fonctionnalités, debugging à faire en vue de version stable
    
==== v1.0.27

    * Simplifié l'ajout/suppression des services
    * Commencé à résoudre les problèmes LightBulbs mais pas terminé
    
==== v1.0.26

    * Gestion pourcentage batterie via le type générique "BATTERY"
    * Si < 20% on set un flag "LowBattery" dans Homekit pour afficher dans Maison/Eve/...
    * Gestion du "charge en cours" définit sur "non chargeable" pour l'instant car il faut voir comment on gère ca coté Jeedom

==== v1.0.25 

    * Nettoyage du code et simplification
    * Meilleure gestion des services en cas de modification de ceux-ci (modification des types génériques)

==== v1.0.24

    * Optimisation (on break les boucles si on a trouvé l'élément, plus rapide sur les grosses installations)

==== v1.0.23

    * si un volet est ouvert à 95% afficher 100% dans Maison (usure mécanique, recalibration)

==== v1.0.22

    * Préparation des Sonnettes en prévision du support dans HomeKit par Apple

==== v1.0.21

    * Corrigé la gestion des Serrures, elles fonctionnent
        *!!! si vous utilisez un iPad comme concentrateur HomeKit, pensez a désactiver Siri pour éviter à qqun de crier "siri ouvre la porte d'entrée" par la boite aux lettres (c'est arrivé !) !!!*

==== v1.0.20

    * Logs plus clairs et plus de verbosité sur la création des Characteristics

==== v1.0.19

    * Support pour les portes de garage/barrières, N'utiliser que BARRIER_STATE ou GARAGE_STATE (même traitement, états 255,254,253,252,0) et GB_TOGGLE

==== v1.0.18

    * Combiné les types OPENING et OPENING_WINDOW car c'est un même type dans homebridge.
    * Ajout du Model (nom du type de l'eqLogic) et du Serial Number (id de l'objet + id logique) dans homebridge.

==== v1.0.17

    * Prise en charge du niveau de debug du plugin mobile (il faut sauver le niveau et relancer le demon pour prise en charge)
    * Simplification du code (retiré des choses inutiles comme la création d'un serveur http)

==== v1.0.16

    * activation d'un mode debug dans la plateforme, il sera lié au status du plugin.
    * Françisation des messages du log, plus de verbosité, plus de clareté et de détails pour encore mieux vous aider en cas de problème.
    * Modification des paramètres de composition des UUID, uniquement l'id jeedom et le nom du périphérique (la pièce jeedom entrait en considération).
[IMPORTANT]
Cela signifie que à l'installation de cette version, vos périphériques dans Maison vont disparaitre pour réapparaitre dans la pièce par défaut (et casser vos scènes et automations).

        ** Point positif : vous pouvez maintenant changer de pièce dans jeedom les périphériques sans les perdre dans Maison. Malheureusement, ils ne changeront pas dans Maison (non-implémenté dans homebridge).
        ** j'ai gardé le nom du périphérique pour l'instant dans l'identifiant car le renommage d'un périphérique dans jeedom casserait tout dans Maison (pour l'instant) de toute façon.
    * Modification du délais d'interrogation-longue pour optimiser les systèmes avec moins de changements d'états.
    * Modification du modèle de fonctionnement. Maintenant on prend un état des périphérique au démarrage du plugin et on le met à jour en temps réèl à chaque changement dans jeedom ou Maison. Moins de requêtes sur l'API jeedom, plus petits temps de réponse dans Maison.
    * Ajout d'un ramasse miettes à la fin de l'ajout des périphériques présent dans jeedom à homebridge, tout ce qui n'a pas été ajouté/modifié est supprimé d'homebridge (si vous avez rendu invisible un périf ou supprimé dans jeedom par exemple).
    * Suppression du bouton Regénérer le fichier de configuration : plus besoin, lorsqu'on sauvegarde la configuration, on regénère le fichier automatiquement et on relance le Daemon.
    * Suppression du bouton Effacer le cache : plus besoin, on gère la suppression individuelle des périphériques. 
[TIP]
Si vous avez un problème avec un périphérique malgré tout : décochez "Envoyer à HomeBridge" | relancez le daemon | décochez "Envoyer à HomeBridge" | relancez le daemon : il sera recréé tout proprement (et dans la pièce par défaut de Maison).

    * Ajout d'avertissements et de messages d'attention si on s'approche du nombre fatidique de 100 accessoires envoyés dans homebridge (HomeKit ne supporte pas plus de 100 accessoires).
    * Au démarrage du daemon, vérification si avahi-daemon et dbus sont bien lancés, sinon, les démarrer.
    * A l'install des dépendances, passer avahi-daemon et dbus à enabled si pas le cas.
    * Corrections diverses, simplifications et optimisations.



== KNOWN ISSUES
  * Possibles problèmes sur les ampoules (voir todo) mais il existait déjà.
  * Possibles problèmes sur certains types génériques plus rares.
  * Alarme et Thermostat peuvent ne pas fonctionné comme désiré, correction prochaines version
  
== TODO | ROADMAP
  * V - Champ textfield custom dans la configuration pour ceux qui veullent rajouter des accessories manuellement dans homebridge (Sonos etc).
  * Modulariser les périphériques : afin de clarifier et de simplifier l'ajout de gestions de nouveaux types.
  * Corriger un bug dans les lightbulbs, set à false la color (pré-existant).
  * V - Modifier un perif (ajout modif supp services) et reparser ses services (reuse function ?)
  * Ajouter des accessoires supportés (Camera, double relay, etc)
  * Comme les pièces ne sont pas portée dans Maison, donner l'option d'un préfix ou sufix nom de la pièce pour avoir facile à les ranger dans Maison (mais il faut renommer pour siri... donc on laisse le choix)
  * Investiguer pour recharger les accessoires sans relancer le daemon.
  * la vérification du status de dépendances homebridge doit inclure la version homebridge required et HAP-NodeJS etc
  * V - lors d'un update du plugin, relancer les dépendances et relancer le daemon
  * V - interdire ces codes pin : 000-00-000, 111-11-111 -> 999-99-999, 123-45-678, 876-54-321
  * ...
