name: Build

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i
      - name: eslint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: .
      - name: Run scan with JSHint
        run: |
          jshint --exclude="node_modules/" --reporter=unix .
